// utils/definitions.js

export const METRIC_DEFINITIONS = {
  netRevenue: {
    title: "Net Revenue",
    insight: "Your True Income. We now explicitly subtract Commissions (Marketplace/Affiliate fees) along with GST, discounts, and returns.",
    goodIf: "Growing M-o-M"
  },
  // ... existing definitions ...
  cmDollars: {
    title: "Contribution Margin",
    insight: "The cash generated by sales to pay for your Team (OpEx) and Marketing.",
    goodIf: "> 25-30% of Revenue"
  },
  ebitda: {
    title: "EBITDA",
    insight: "Operational Profit before Tax/Interest.",
    goodIf: "Positive"
  },
  mer: {
    title: "MER (ROAS)",
    insight: "Total Revenue / Total Ad Spend.",
    goodIf: "> 3.0"
  },
  blendedCac: {
    title: "Blended CAC (New Cust Only)",
    insight: "Cost to acquire a NEW customer. This metric intentionally IGNORES returning customers to show the true cost of growth.",
    goodIf: "< 30% of AOV"
  },
  costPerOrder: { 
    title: "Marketing Cost Per Order (CPO)", // <--- NEW
    insight: "The average ad cost for ANY order (New + Returning). If you have high repeat rates, this will be much lower than your CAC.",
    goodIf: "< 20% of AOV"
  },
  safeMaxCpa: {
    title: "Safe Max CPA",
    insight: "Your bid limit. Do not pay more than this for a new customer.",
    goodIf: "Higher than CAC"
  },
  netBurn: {
    title: "True Cash Burn",
    insight: "Cash leaving the bank (including Inventory purchases).",
    goodIf: "Negative (Cash Gen)"
  }
};